import { Footer } from "@/components/footer/footer";

import { routing } from "@/i18n/routing";
import { fontVariables } from "@/lib/font";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import "./../globals.css";

export const metadata: Metadata = {
  title: "ICSA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontVariables} antialiased`}>
        <NextIntlClientProvider>
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
